POST http://localhost:8081/consultation
Content-Type: application/json

{
  "startDateTime": "2025-04-08T13:00:00.000+03:00",
  "consultationSlot": {
    "id": "f96bbf39-ccdf-430d-99d3-881cfd4bc288"
  }
}