GET http://localhost:8080/profile
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJjcmVkZW50aWFsc05vbkV4cGlyZWQiOnRydWUsImFjY291bnROb25FeHBpcmVkIjp0cnVlLCJpZCI6ImNkMjhlYzQ5LTlkYzctNDgzNy1hZmQwLTFkODU0MDM2ZWI3YyIsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1BBVElFTlQifV0sImVuYWJsZWQiOnRydWUsInVzZXJuYW1lIjoibG9naW4iLCJhY2NvdW50Tm9uTG9ja2VkIjp0cnVlLCJzdWIiOiJsb2dpbiIsImlhdCI6MTc0MzAzNjAxNywiZXhwIjoxNzQzMDM2MzE3fQ.3kZUtghFLQwLmlqE1tXH8JRwwxKH4oycV0mDarrVv4OilMJBzvy4q6meuomkkJY6Wq_BhJ90xTEzuZkoHyQY8w
